---
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-down
- hosts: k3s_worker
  roles:
    - k3s-worker-down
- hosts: k3s_master
  roles:
    - k3s-master-down
  run_once: yes
- hosts: all
  roles:
    - docker-down
- hosts:
    - raspberry_pi_os
    - ubuntu
  roles:
    - debian-down
- hosts: ubuntu
  roles:
    - ubuntu-down
- hosts: raspberry_pi_os
  roles:
    - raspberry-pi-os-down
- hosts: raspberry_pi_hw
  roles:
    - raspberry-pi-hw-down
