---
- hosts: raspberry_pi
  roles:
    - raspberry-pi-up
- hosts:
    - raspbian
    - ubuntu
  roles:
    - debian-up
- hosts:
    - ubuntu:&raspberry_pi
  roles:
    - ubuntu-raspberry-pi-up
- hosts: raspbian
  roles:
    - raspbian-swap-down
- hosts: ubuntu
  roles:
    - ubuntu-swap-down
- hosts: all
  roles:
    - docker-up
- hosts: k3s_master
  roles:
    - k3s-master-up
- hosts: k3s_worker
  roles:
    - k3s-worker-up
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-up
- hosts: k8s_master
  roles:
    - k8s-master-up
- hosts: k8s_worker
  roles:
    - k8s-worker-up
